export const menuItems = [
  {
    id: "streamline",
    title: "Streamline",
    path: "/streamline",
    description: "Học nghe nói tiếng Anh",
    image: "https://magical-tulumba-581427.netlify.app/img-ui/streamline.png",
    alt: "Streamline",
    category: "Học tập",
    priority: "high",
  },
  {
    id: "lessons1000",
    title: "1000 Bài luyện",
    path: "/lessons1000",
    description: "Luyện tập toàn diện",
    image: "https://magical-tulumba-581427.netlify.app/img-ui/home-nobita.png",
    alt: "1000 Bài luyện",
    category: "Học tập",
    priority: "high",
  },
  {
    id: "video",
    title: "Nộp bài nói",
    path: "/speaking-upload",
    description: "Quay video nói tiếng Anh",
    image:
      "https://magical-tulumba-581427.netlify.app/img-ui/nobita-submit.png",
    alt: "Nộp bài nói",
    category: "Thực hành",
    priority: "high",
  },
  {
    id: "flashcard",
    title: "Flashcard",
    path: "/flashcard",
    description: "Học từ vựng hiệu quả",
    image: "/assets/images/flash-card.png",
    alt: "Flashcard",
    category: "Học tập",
    priority: "medium",
  },
  {
    id: "grammar",
    title: "Giải toàn bộ ngữ pháp 6-12",
    path: "/grammar",
    description: "Học ngữ pháp qua video",
    image: "https://magical-tulumba-581427.netlify.app/img-ui/sizuka.png",
    alt: "Ngữ pháp",
    category: "Học tập",
    priority: "medium",
  },
  {
    id: "shopping",
    title: "Nobita đi Shopping",
    path: "/shopping",
    description: "Mua sắm với điểm thưởng",
    image:
      "https://magical-tulumba-581427.netlify.app/img-ui/nobita-shopee.png",
    alt: "Shopping",
    category: "Xã hội",
    priority: "low",
  },
  {
    id: "class",
    title: "Lớp học",
    path: "/classes",
    description: "Tham gia lớp học trực tuyến",
    image: "/assets/images/class.jpg",
    alt: "Lớp học",
    category: "Học tập",
    priority: "high",
  },
  {
    id: "spin-dorayaki",
    title: "Vòng quay bánh rán",
    path: "/spin-dorayaki",
    description: "Tham gia vòng quay bánh rán",
    image: "/assets/spin-dorayaki/spin.jpg",
    alt: "Vòng quay bánh rán",
    category: "Xã hội",
    priority: "high",
  },
];
